{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "bdapp.fullname" . }}
  namespace: {{ default "default" .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
    konghq.com/preserve-host: "false"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "bdapp.fullname" . }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ include "bdapp.fullname" . }}
            port:
              number: {{ .Values.service.port }}
        path:  {{ .Values.ingress.path }}
        pathType: Prefix
{{- end -}}