apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdapp.fullname" . }}
  namespace: {{ default "default" .Values.namespace }}
  labels:
    {{- include "bdapp.labels" . | nindent 4 }}
  annotations:
    {{ if eq .Values.service.type "LoadBalancer" }}
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-scheme: internal
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}  
      targetPort: http
      name: http
  selector:
    {{- include "bdapp.selectorLabels" . | nindent 4 }}