apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost-dev
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/<your-username>/<your-repo>.git
    targetRevision: main
    path: devopsapp
    helm:
      valueFiles:
        - ../values/kubecost/value-dev.yml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
