{{- if (.Values.clusterController).enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubecost.clusterController.name" . }}
  labels:
      {{- include "kubecost.commonLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubecost.clusterController.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubecost.clusterController.name" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}