{{- if or .Values.cloudCost.cloudIntegrationJSON .Values.kubecostProductConfigs.cloudIntegrationJSON }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kubecost.cloudCost.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  {{- if .Values.cloudCost.cloudIntegrationJSON }}
  cloud-integration.json: {{ .Values.cloudCost.cloudIntegrationJSON | replace "\n" "" | b64enc }}
  {{- end }}
  {{- if .Values.kubecostProductConfigs.cloudIntegrationJSON }}
  cloud-integration.json: {{ .Values.kubecostProductConfigs.cloudIntegrationJSON | replace "\n" "" | b64enc }}
  {{- end }}
{{- end -}}
