{{- if and .Values.serviceAccount.create .Values.cloudCost.serviceAccountName }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kubecost.cloudCost.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.cloudCost.commonLabels" . | nindent 4 }}
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
