{{- if .Values.global.containerRequestRightSizingReports }}
{{- if .Values.global.containerRequestRightSizingReports.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ default "crrs-configs" .Values.containerRequestRightSizingReportConfigmapName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  crrs-reports.json: '{{ toJson .Values.global.containerRequestRightSizingReports.reports }}'
{{- end -}}
{{- end -}}

