{{- if not (.Values.global.federatedStorage).existingSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Release.Name }}-federated-storage-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  {{- include "kubecost.federatedStorage.fileName" . | nindent 2}}: {{ (include "kubecost.federatedStorage.config" . ) | b64enc }}
{{- end }}
