{{- if and (.Capabilities.APIVersions.Has "route.openshift.io/v1/Route") (.Values.global.platforms.openshift.enabled) (.Values.global.platforms.openshift.route.enabled) }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "kubecost.fullname" . }}-route
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
  {{- with .Values.global.platforms.openshift.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.global.platforms.openshift.route.host }}
  host: "{{ .Values.global.platforms.openshift.route.host }}"
  {{- end }}
  port:
    targetPort: tcp-frontend
  tls:
    termination: edge
  to:
    kind: Service
    name: {{ include "kubecost.frontend.serviceName" . }}
    weight: 100
  wildcardPolicy: None
{{- end }}
