{{- if eq (include "kubecost.rbacTeams.config.enabled" .) "true" }}
{{- if not .Values.teams.teamsConfigMapName }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "kubecost-rbac-teams-config"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  rbac-teams-configs.json: '{{ toJson .Values.teams.teamsConfig }}'
{{- end }}
{{- end }}