{{- if .Values.oidc }}
{{- if and (not .Values.oidc.existingCustomSecret.enabled) .Values.oidc.secretName }}
{{- if .Values.oidc.clientSecret }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.oidc.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
stringData:
  clientSecret: {{ .Values.oidc.clientSecret }}
{{- end -}}
{{- end -}}
{{- end -}}
