{{- if and ((.Values.kubecostProductConfigs).smtp).config (not ((.Values.kubecostProductConfigs).smtp).secretname) }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "kubecost.smtp.secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecost.commonLabels" . | nindent 4 }}
data:
  smtp.json: {{  .Values.kubecostProductConfigs.smtp.config | b64enc }}
{{- end -}}
